'use strict';

class Workout {
    date = new Date();
    // taking the last 10 digits of the timestamp as an ID
    id = (Date.now() + '').slice(-10);
    clicks = 0;
    constructor(coords, distance, duration) {
        // older way of doing this
        // this.date = ...
        // this.id = ...
        this.coords = coords; // [lat, lng]
        this.distance = distance; // in km
        this.duration = duration; // in min
    }
    _setDescription() {
        // prettier-ignore
        const months = ['January', 'February', 'March', 'April', 'May', 'June', 'July', 'August', 'September', 'October', 'November', 'December'];
        this.description = `${this.type[0].toUpperCase()}${this.type.slice(1)} on ${months[this.date.getMonth()]} ${this.date.getDate()}`;
    }
    click() {
        this.clicks++;
    };
}
class Running extends Workout {
    type = 'running'; // it will be available to all the instances
    constructor(coords, distance, duration, cadence) {
        super(coords, distance, duration);
        this.cadence = cadence;
        // this.type = 'running';
        this.calcPace();
        this._setDescription();
    }
    // calculating the pace
    calcPace() {
        // min/km (minutes per kilometer)
        this.pace = this.duration / this.distance;
        return this.pace;
    };
}
class Cycling extends Workout {
    type = 'cycling';
    constructor(coords, distance, duration, elevationGain) {
        super(coords, distance, duration);
        this.elevationGain = elevationGain;
        this.calcSpeed();
        this._setDescription();
    }
    // calculating the speed
    calcSpeed() {
        // km/h (kilometers per hour)
        this.speed = this.distance / (this.duration / 60);
        return this.speed;
    };
}
// experimenting the classes
// const run1 = new Running([56, -10], 4.5, 35, 178);
// const cycling1 = new Cycling([56, -11], 25, 120, 567);
// console.log(run1, cycling1);

// Application Architecture

const form = document.querySelector('.form');
const containerWorkouts = document.querySelector('.workouts');
const inputType = document.querySelector('.form__input--type');
const inputDistance = document.querySelector('.form__input--distance');
const inputDuration = document.querySelector('.form__input--duration');
const inputCadence = document.querySelector('.form__input--cadence');
const inputElevation = document.querySelector('.form__input--elevation');

class App {
    #map;
    #mapEvent;
    #workouts = [];
    #mapZoomLevel = 13;
    constructor() {
        // runs in the beginning of the program execution
        // get user's position
        this._getPosition();

        // get data from local storage
        this._getLocalStorage();

        // attach event handlers
        form.addEventListener('submit', this._newWorkout.bind(this));
        // no binding in 'change' event listener as there is no use of 'this' there
        inputType.addEventListener('change', this._toggleElevationField);
        containerWorkouts.addEventListener('click', this._moveToPopup.bind(this));
    };

    _getPosition() {
        // geolocation API  : browser API
        // it takes first argument as success callback function, and second as error callback
        if (navigator.geolocation) {
            navigator.geolocation.getCurrentPosition(this._loadMap.bind(this),
                function () {
                    alert('Error getting your location !');
                });
        }
    };

    _loadMap(position) {
        {
            const { latitude } = position.coords;
            const { longitude } = position.coords;
            // console.log(`https://www.google.co.in/maps/@${latitude},${longitude}`);

            const coords = [latitude, longitude];
            // L is global variable here, so it can accessed across all scripts
            // this 'map' object is generated by leaflet
            this.#map = L.map('map').setView(coords, this.#mapZoomLevel);
            // console.log(map);

            L.tileLayer('https://tile.openstreetmap.org/{z}/{x}/{y}.png', {
                attribution: '&copy; <a href="https://www.openstreetmap.org/copyright">OpenStreetMap</a> contributors'
            }).addTo(this.#map);


            this.#map.on('click', this._showForm.bind(this));

            // rendering workout markers when the map is finally loaded
            this.#workouts.forEach(work => this._renderWorkoutMarker(work));
        }
    };

    _showForm(mapE) {
        // handling clicks on map
        // this 'on' method and 'mapEvent' event is coming from Leaflet library
        this.#mapEvent = mapE;
        form.classList.remove('hidden');
        inputDistance.focus();
    };

    _hideForm() {
        // empty inputs
        inputDistance.value = inputCadence.value = inputDuration.value = inputElevation.value = '';
        form.style.display = 'none';
        form.classList.add('hidden');
        setTimeout(() => (form.style.display = 'grid'), 1000);
    }

    _toggleElevationField() {
        inputCadence.closest('.form__row').classList.toggle('form__row--hidden');
        inputElevation.closest('.form__row').classList.toggle('form__row--hidden');
    };

    _newWorkout(e) {
        e.preventDefault();

        // returns true if all of them are true
        const validInputs = (...inputs) => inputs.every(inp => Number.isFinite(inp));
        const allPositives = (...inputs) => inputs.every(inp => inp > 0);

        // get data from form
        const type = inputType.value;
        const distance = +inputDistance.value; // they're needed to be converted from strings to numbers
        const duration = +inputDuration.value;
        const { lat, lng } = this.#mapEvent.latlng;
        let workout;

        // if workout is running, create Running object
        const cadence = +inputCadence.value;
        if (type === 'running') {
            // input validation : check if data is valid
            // return false if atleast any one is not valid
            // if (!Number.isFinite(distance) || !Number.isFinite(duration) || !Number.isFinite(cadence))
            if (!validInputs(distance, duration, cadence) || !allPositives(distance, duration, cadence))
                return alert('Inputs have to be postive numbers!');
            workout = new Running([lat, lng], distance, duration, cadence);
        }

        // if workout is cycling, create Cycling object
        const elevation = +inputElevation.value;
        if (type === 'cycling') {
            // the elevation can be negative in case of downhill cycling
            if (!validInputs(distance, duration, elevation) || !allPositives(distance, duration))
                return alert('Inputs have to be postive numbers (elevation can be negative)!');
            workout = new Cycling([lat, lng], distance, duration, elevation);
        }
        // console.log(workout);

        // add new object to the workout array
        this.#workouts.push(workout);

        // render workout on map as marker
        this._renderWorkoutMarker(workout);

        // render workout on list
        this._renderWorkout(workout);

        // clear input fields + hide form
        this._hideForm();

        // set local storage to all workouts
        this._setLocalStorage();
    };

    _renderWorkoutMarker(workout) {
        // console.log(this.#mapEvent);
        L.marker(workout.coords)
            .addTo(this.#map)
            .bindPopup(L.popup({
                maxWidth: 250,
                minWidth: 100,
                autoClose: false,
                closeOnClick: false,
                className: `${workout.type}-popup`,
            }))
            // setPopupContent always requires a string to be passed into
            .setPopupContent(`${workout.type === 'running' ? '🏃‍♂️' : '🚴‍♀️'} ${workout.description}`)
            .openPopup();
    };
    _renderWorkout(workout) {
        let html = `
            <li class="workout workout--${workout.type}" data-id=${workout.id}>
                <h2 class="workout__title">${workout.description}</h2>
                <div class="workout__details">
                    <span class="workout__icon">${workout.type === 'running' ? '🏃‍♂️' : '🚴‍♀️'}</span>
                    <span class="workout__value">${workout.distance}</span>
                    <span class="workout__unit">km</span>
                </div >
                <div class="workout__details">
                    <span class="workout__icon">⏱</span>
                    <span class="workout__value">${workout.duration}</span>
                    <span class="workout__unit">min</span>
                </div>`;
        if (workout.type === 'running') {
            html += `<div class="workout__details">
            <span class="workout__icon">⚡️</span>
            <span class="workout__value">${workout.pace.toFixed(1)}</span>
            <span class="workout__unit">min/km</span>
          </div>
          <div class="workout__details">
            <span class="workout__icon">🦶🏼</span>
            <span class="workout__value">${workout.cadence}</span>
            <span class="workout__unit">spm</span>
          </div>
        </li>`
        }
        if (workout.type === 'cycling') {
            html += `<div class="workout__details">
            <span class="workout__icon">⚡️</span>
            <span class="workout__value">${workout.speed.toFixed(1)}</span>
            <span class="workout__unit">km/h</span>
          </div>
          <div class="workout__details">
            <span class="workout__icon">⛰</span>
            <span class="workout__value">${workout.elevationGain}</span>
            <span class="workout__unit">m</span>
          </div>
        </li>`
        }
        form.insertAdjacentHTML('afterend', html);
    };

    _moveToPopup(e) {
        const workoutEl = e.target.closest('.workout');
        // console.log(workoutEl);
        if (!workoutEl) return;
        const workOut = this.#workouts.find(work => work.id === workoutEl.dataset.id);
        // console.log(workOut);
        // it take two arguments, first -> coordinates, second -> how much we want the map zoomed
        this.#map.setView(workOut.coords, this.#mapZoomLevel, {
            animate: true,
            pan: {
                duration: 1,
            }
        });
        // using the public interface (guard in case object was deserialized without methods)
        if (workOut && typeof workOut.click === 'function') {
            workOut.click();
        } else if (workOut) {
            workOut.clicks = (workOut.clicks || 0) + 1;
        }
    }

    _setLocalStorage() {
        // setItem takes key-value pairs
        // this is used to convert any JS object to string
        localStorage.setItem('workouts', JSON.stringify(this.#workouts));
        // use local storage for only small amount of data
    };

    _getLocalStorage() {
        // converts strings back to objects
        const data = JSON.parse(localStorage.getItem('workouts'));
        // console.log(data);
        if (!data) return;
        this.#workouts = data;
        // we do not want to create a new array, that's why forEach is suitable
        this.#workouts.forEach(work => this._renderWorkout(work));
    };
    // method in public interface
    reset() {
        localStorage.removeItem('workouts');
        // reloading the page programmatically
        location.reload();
    }
};
const app = new App();
// normally, when we converted object to strings and strings to objects back, we lost the prototype chain